### ISSUE TITLE
Got error 'Unexpected token' when I change to use src instead of dist

### ISSUE THREAD

**Issue by nvtin** [SpoonX/aurelia-datatable#97]
Hi everybody.
I searched, checked code and saw that this component did not support disable/enable search for every field (like populate for sort) to limit search fields.
such as: I have 3 columns but I just allow to search on 2 columns. so the idea is add one more option on column to disable or enable search field on dropdown list.
Actually I want to contribute it but when I change aurelia.json to use src code instead of dist, I got error.
Here is my aurelia.json
```
        ....
         {
            "name": "homefront",
            "path": "../node_modules/homefront/dist",
            "main": "index"
          },
          {
            "name": "aurelia-datatable",
            "path": "../node_modules/aurelia-datatable/src",
            "main": "index",
            "resources": [
              "bootstrap/datatable.html"
            ]
          },
         ....

```

and I got error like this

> Tracing aurelia-datatable...
commonJs.convert: COULD NOT CONVERT: /Users/nvtin/workspace/demo/node_modules/aurelia-datatable/src/index.js, so skipping it. Error was: Error: Line 1: Unexpected token
Error occurred while tracing
Error: Parse error using esprima for file: /Users/nvtin/workspace/demo/node_modules/aurelia-datatable/src/index.js
Error: Line 1: Unexpected token
    at Object.context.load (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:392:21)
    at Module.load (eval at <anonymous> (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:832:29)
    at Module.fetch (eval at <anonymous> (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:822:66)
    at Module.check (eval at <anonymous> (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:854:30)
    at Module.enable (eval at <anonymous> (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1173:22)
    at Object.enable (eval at <anonymous> (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1554:39)
    at Object.context.enable (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:292:24)
    at Module.eval (eval at <anonymous> (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:1158:33)
    at eval (eval at <anonymous> (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:134:23)
    at each (eval at <anonymous> (/Users/nvtin/workspace/demo/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:1), <anonymous>:59:31)

So I dont know why this happen. Can you guys give me solution to fix it? so I can run and contribute it.
@RWOverdijk  How do you think?

**Comment by RWOverdijk** [comment]
@jeremyvergnas You're the search master!

@nvtin afaik running from dist has never been possible.

**Comment by nvtin** [comment]
Hi guys. nobody help for search? I really want to contribute about search but I can't run with src directory.
```
commonJs.convert: COULD NOT CONVERT: /Users/nvtin/workspace/demo/node_modules/aurelia-datatable/src/index.js, so skipping it. Error was: Error: Line 1: Unexpected token
```
So I will make new issue to request support about limited search field

**Comment by RWOverdijk** [comment]
@nvtin I know you can use link with jspm. Surely there's a link for your tooling?
